name: "with a output file"
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t built-image:scan .
      - name: Run dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: 'built-image:scan'
          format: 'json'
          output: 'result.json'
          exit-code: '1'
          exit-level: 'warn'
          ignore: 'CIS-DI-0001,DKL-DI-0006,DKL-LI-0001'
          accept-file: 'credentials.json'
          accept-key: 'MYSQL_PASSWD'
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Report
          path: result.json
